---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-store
  labels:
    app: memory-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-store
  template:
    metadata:
      labels:
        app: memory-store
    spec:
      containers:
        - name: memory-store
          image: julepai/memory-store:${TAG}
          ports:
            - containerPort: 9070
          env:
            - name: COZO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cozo-secrets
                  key: COZO_AUTH_TOKEN
            - name: COZO_PORT
              value: "${COZO_PORT:-9070}"
            - name: COZO_MNT_DIR
              value: "${MNT_DIR:-/data}"
            - name: COZO_BACKUP_DIR
              value: "${COZO_BACKUP_DIR:-/backup}"
          volumeMounts:
            - name: cozo-data
              mountPath: /data
            - name: cozo-backup
              mountPath: /backup
      volumes:
        - name: cozo-data
          persistentVolumeClaim:
            claimName: cozo-data
        - name: cozo-backup
          persistentVolumeClaim:
            claimName: cozo-backup
