apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-store
  template:
    metadata:
      labels:
        app: memory-store
    spec:
      containers:
      # Main memory-store container
      - name: memory-store
        image: julepai/memory-store:latest
        envFrom:
        - configMapRef:
            name: memory-store-config
        - secretRef:
            name: security-secret
        ports:
        - containerPort: 9070
        volumeMounts:
        - name: cozo-data
          mountPath: /data
        - name: cozo-backup
          mountPath: /backup

      # Sidecar container for backup cron
      - name: backup-cron
        image: bitnami/kubectl:latest
        volumeMounts:
        - name: cozo-backup
          mountPath: /backup
        command: ["/bin/sh", "-c"]
        args:
          - |
            while true; do
              echo "Running backup";
              bash /app/backup.sh;
              sleep 10800;  # Run every 3 hours
            done;

      volumes:
      - name: cozo-data
        persistentVolumeClaim:
          claimName: cozo-data-pvc
      - name: cozo-backup
        persistentVolumeClaim:
          claimName: cozo-backup-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: memory-store
  labels:
    app: memory-store
spec:
  selector:
    app: memory-store
  ports:
    - protocol: TCP
      port: 9070
      targetPort: 9070