# kubectl apply -f volume.yaml

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cozo-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cozo-backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi